services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    container_name: mysql_sticky
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: fluxi
      MYSQL_PASSWORD: admin